# Default values for otus-auth-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

fullnameOverride: "books-otus"

image: jawello/books-otus:0.0.1

data_generation:
  enabled: true
  image: jawello/books-otus-data-generator:0.0.1
  products_count: 10000
  loglevel: WARNING

service:
  type: NodePort
  port: 7000

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "nginx"
  hosts:
    - host: arch.homework
      paths:
        - /products
        - /products_search

metrics:
  enabled: false
  serviceMonitor:
    enabled: false

postgresql:
  enabled: true
  postgresqlUsername: postgres
  postgresqlPassword: otus
  postgresqlDatabase: postgres
  service:
    port: "5432"
  metrics:
    enabled: false
    service:
      type: NodePort
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9187"
    serviceMonitor:
      enabled: false
      additionalLabels: {}
      namespace: monitoring
      interval: 30s
      scrapeTimeout: 10s

redis:
  enabled: true
  usePassword: false
  redisPort: "6379"
  cluster:
    enabled: false
  metrics:
    enabled: false
    service:
      type: NodePort
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9187"
    serviceMonitor:
      enabled: false
      additionalLabels: {}
      namespace: monitoring
      interval: 30s
      scrapeTimeout: 10s